apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
spec:
  selector:
    matchLabels:
      app: my-node-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-node-app
        env: development
    spec:
      containers:
      - name: my-app
        image: hello-node
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
       
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-node-service
spec:
  type: LoadBalancer
  ports:
  - port: 3500
    targetPort: 8080
    protocol: "TCP"
  selector:
    app: my-node-app